### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by Macacoazul01**
## 0.2.5+1
 - Readme update.

## 0.2.5
 - Partial error handling to stop cors related problems on web.
 - Package rename.

## 0.2.4
 - Allow the user to initialize the class with default maximum value of decimal places for the currencies.

## 0.2.3
 - Allow the user to initialize the class with default values for source and destination currencies.

## 0.2.2
 - Allow the user to update the currencies.

## 0.2.1
 - Added default conversion + mini improvements.

## 0.2.0
 - Removed repetitive code and added sample app.
 
 
## 0.1.0
- Updated dependencies and removed repetitive code.

### CODE REVIEW

**Comment by hamzakhurshid12** [comment]
@Macacoazul01 can you please add some details on what you did in these comments? This will help me to look for specific changes and create test cases before approving your changes.
Thank you.

**Comment by Macacoazul01** [comment]
@hamzakhurshid12 they are on the changelog

**Comment by Macacoazul01** [comment]
Any expectations on when this will be merged and published?

**Comment by Macacoazul01** [comment]
That makes no sense for me to publish the updated copy of this package on pub if your gonna keep maintaining. But if you're gonna drop the support I'll launch the v2

**Comment by Macacoazul01** [comment]
@hamzakhurshid12

**Comment by Macacoazul01** [comment]
Like the updates won't land here i'm gonna republish the package

**Comment by hamzakhurshid12** [comment]
Hi @Macacoazul01 I am going to review your PR today!

**Comment by hamzakhurshid12** [comment]
That's amazing work @Macacoazul01. Impressed by your vision and hard work. I apologize for not getting back to you the past few weeks. It's merged now!

**Comment by hamzakhurshid12** [comment]
@Macacoazul01 I have added you as a collaborator on this repository. Please share your email that can be added on Pub.dev as a package uploader. I apologize for not being able to answer you for a long time. It would be great if you can merge changes from your fork here and help the hundreds of users of this package together.

**Comment by Macacoazul01** [comment]
gian.b.bettega@gmail.com

**Pull request merged**
